kind: Pod
apiVersion: v1
metadata:
  name: configmapandsecretes1
  labels:
    app: nginx-app1
spec:
  containers:
  - name: myapp-container
    image: busybox:1.28
    envFrom:
    - configMapRef:
        name: demo-configmap
    command: ['sh', '-c', 'echo This app is running && sleep 3600']

