kind: Pod
apiVersion: v1
metadata:
  name: secretes
  labels:
    app: nginx-app
spec:
  containers:
  - name: myapp-container
    image: busybox:1.28
    env:
    - name: FIRSTNAME
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: password
    command: ['sh', '-c', 'echo This app is running && sleep 3600']

