kind: Pod
apiVersion: v1
metadata:
  name: nginx-pod
  labels:
    env: demo
    type: frontend
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelector:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd
