apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    app: nginx
spec:
  template:
    metadata:
      labels:
        app: nginx
      name: nginx-rs
    spec:
      containers:
      - image: nginx
        name: nginx-controller
        ports:
        - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      app: nginx
