apiVersion: trainwithshubham.com/v1
kind: DevOpsBatch

metadata:
  name: devops-batch-1
  namespace: default

spec:
  name: "Kubernetes Zero to Hero"
  duration: "6 Months"
  mode: "Live"
  platform: "Zoom"