kind: Deployment
apiVersion: app/v1
metadata:
  name: nginx-deployment
  labels:
    env: dev
    app: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx-app
      env: dev
  template:
    metadata:
      name: nginx-dop-app
      labels:
        app: nginx-dop
        env: dev
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
  replicas: 3