kind: replicationController
apiVersion: v1
metadata:
  name: nginx-rc
  labels:
    app: nginx-app
    env: dev
spec:
  template:
    metadata:
      labels:
        app: nginx-app
        env: dev
    spec:
      containers:
        - name: nginx-pod
          image: nginx:latest
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
      env: dev