kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: nginx-rs
  labels:
    app: nginx-rs
    env: dev
spec:
  selector:
    matchLabels:
      app: nginx-rs-pod
      env: dev
    matchExpressions:
    - key: env
      operator: In
      values:
      - dev
      - test
  template:
    metadata:
      labels:
        app: nginx-rs-pod
        env: dev
    spec:
      containers:
        - name: nginx-pod
          image: nginx:latest
          ports:
            - containerPort: 80
  replicas: 3
