kind: DeamonSet
apiVersion: apps/v1
metadata:
  name: nginx-deamonset
  namespace: nginx
  labels:
    app: nginx-deamonset
spec:
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      name: nginx-deamon-pod
      labels:
        app: nginx-pod
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80

