kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mycluster 

nodes:
- roles: control-plane
  image: kindest/node:v1.24.0
  extraPortMappings:
  - containerPort: 30080
    hostPort: 8080
    protocol: TCP

- roles: worker
  image: kindest/node:v1.24.0

- roles: worker
  image: kindest/node:v1.24.0
