kind: CronJob
apiVersion: batch/v1
metadata:
  name: demo-cronjob
  namespace: nginx
spec:
  shedule: "*/1 * * * *"
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      template:
        metadata:
          name: demo-cronjob
          labels:
            app: demo-cronjob
        spec:
          containers:
          - name: demo-cronjob
            image: busybox:latest
            command: ["echo", "Hello, World! && seep 10"]
          restartPolicy: Never