kind: Job
apiVersion:  batch/v1
metadata:
  name: demo-job
  namespace: nginx
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: demo-job
      labels:
        app: demo-job
    spec:
      containers:
      - name: demo-job
        image: busybox:latest
        command: ["echo", "Hello, World! && seep 10"]
      restartPolicy: Never

