kind: Deployment
apiVersion: apps/v1
metadata:
  name: php-apache
spec:
  selector:
    matchLabels:
      run: php-apache
  template:
    metadata:
      name:  php-apache
      labels:
        run: php-apache
    spec:
      containers:
        - name: php-container
          image: registory.k8s.io/hpa-example
          ports:
          - containerPort: 80
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m

---
apiVersion: v1
kind: Service
metadata:
  name: hpa-service
spec:
  selector:
    run: php-apache
  ports:
  - port: 80