kind: Pod
apiVersion: v1
metadata:
  name: memory-demo3
  namespace: mem-example
spec:
  containers:
  - name: mem-demo-ctr1
    image: polinux/stress
    resources:
      requests:
        memory: "1000Gi"
      limits:
        memory: "1000Gi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-butes", "250M", "--vm-hang", "1"]
  